using System;
using System.Reflection;

namespace Turquoise.ORM
{
    /// <summary>
    /// Metadata about a mapped field: its DB column name, source table alias,
    /// type information, identity/PK status, and optional encryption/mapper.
    /// </summary>
    public class TargetFieldInfo
    {
        public TargetFieldInfo() { }

        public TargetFieldInfo(TargetFieldInfo source)
        {
            FieldInfo           = source.FieldInfo;
            FieldName           = source.FieldName;
            TargetName          = source.TargetName;
            SourceName          = source.SourceName;
            TargetType          = source.TargetType;
            NativeTargetType    = source.NativeTargetType;
            IsIdentity          = source.IsIdentity;
            IsInPK              = source.IsInPK;
            IsIndexed           = source.IsIndexed;
            IsNullable          = source.IsNullable;
            IsLarge             = source.IsLarge;
            Index               = source.Index;
            MaxLength           = source.MaxLength;
            IsAutoGenerated     = source.IsAutoGenerated;
            GeneratorName       = source.GeneratorName;
            FieldMapper         = source.FieldMapper;
            Encryption          = source.Encryption;
            IsReadOnly          = source.IsReadOnly;
            Scale               = source.Scale;
            Precision           = source.Precision;
        }

        // Reflection handle to the actual field
        public FieldInfo FieldInfo;

        public string   FieldName;          // C# field name
        public string   TargetName;         // DB column name
        public string   SourceName;         // DB table alias / source name
        public Type     TargetType;         // CLR type of the TField subclass

        public string   NativeTargetType;   // Optional native DB type hint (e.g. "varbinary")

        public bool     IsIdentity;
        public bool     IsInPK;
        public bool     IsIndexed;
        public bool     IsNullable  = true;
        public bool     IsLarge;
        public int      Index;
        public bool     IsAutoGenerated;
        public string   GeneratorName;
        public int      Scale;
        public int      Precision;
        public bool     IsReadOnly  { get; set; }
        public int      Length;

        private int _maxLengthInternal;
        public int MaxLength
        {
            get => Encryption != null ? Encryption.GetMaxFieldLength() : _maxLengthInternal;
            set => _maxLengthInternal = value;
        }

        public EncryptionAlgorithm  Encryption  = null;
        public IDBFieldMapper       FieldMapper  = null;

        private static readonly Type _tFieldType     = typeof(TField);
        private static readonly Type _tStringType    = typeof(TString);

        /// <summary>
        /// Read the field value from an object, applying mapper/encryption as required.
        /// </summary>
        public object GetValue(object obj)
        {
            object value = FieldInfo.GetValue(obj);

            if (FieldMapper != null)
            {
                FieldMapper.SetContainingDataObject((DataObject)obj);
                value = FieldMapper.ConvertToDBValue(value);
            }
            else if (FieldInfo.FieldType.IsEnum)
            {
                value = (int)value;
            }
            else if (FieldInfo.FieldType == typeof(TGuid))
            {
                value = value?.ToString();
            }

            if (Encryption != null)
                value = Encryption.Encrypt(value);

            return value;
        }

        /// <summary>
        /// Write a DB value back into the field on an object, unwrapping mapper/encryption.
        /// </summary>
        public void SetValue(object obj, object value)
        {
            if (Encryption != null)
                value = Encryption.Decrypt(value);

            if (FieldMapper != null)
            {
                FieldMapper.SetContainingDataObject((DataObject)obj);
                value = FieldMapper.ConvertFromDBValue(value);
            }
            else if (FieldInfo.FieldType.IsEnum)
            {
                value = Enum.Parse(FieldInfo.FieldType, value.ToString());
            }

            if (FieldInfo.FieldType.IsSubclassOf(_tFieldType))
            {
                TField field = (TField)FieldInfo.GetValue(obj);
                if (field == null)
                {
                    field = TField.Create(FieldInfo.FieldType, (DataObject)obj);
                    field.SetValue(value);
                    field.SetLoaded(true);
                    FieldInfo.SetValue(obj, field);
                }
                else
                {
                    field.SetLoaded(true);
                    field.SetValue(value);
                }
            }
            else
            {
                FieldInfo.SetValue(obj, value);
            }

            if (obj is DataObject dataObject)
                dataObject.SetLoaded(true);
        }
    }
}
